// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotationApp.API.Data;

#nullable disable

namespace QuotationApp.API.Migrations
{
    [DbContext(typeof(QuotationDbContext))]
    [Migration("20261005125405_AddSalesOrderSchema")]
    partial class AddSalesOrderSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuotationApp.API.Data.LoginHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemoteAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HsnCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HsnCode");

                    b.Property<decimal?>("ImplementationEffortCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ImplementationEffortCost");

                    b.Property<int?>("ImplementationEffortManDays")
                        .HasColumnType("int");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NoOfUsersForSingleInstallation")
                        .HasColumnType("int");

                    b.Property<string>("Pillar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ReverseChargeDefault")
                        .HasColumnType("bit")
                        .HasColumnName("ReverseChargeDefault");

                    b.Property<string>("SacCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SacCode");

                    b.HasKey("Id");

                    b.HasIndex("ModuleName")
                        .IsUnique();

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ImplementationPriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ModulePriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuotationNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuotationToAddress")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("QuotationToContactNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("QuotationToEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QuotationToName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReferenceBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ModulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuotationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuotationNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuotationToAddress")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("QuotationToContactNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("QuotationToEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QuotationToName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReferenceBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("OrganizationName", "ModulesJson");

                    b.ToTable("QuotationHistory", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationModuleEntity", b =>
                {
                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImplementationEffortUnit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("ImplementationMultiplier")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ImplementationPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImplementationUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ModulePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ModuleSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NoOfInstallations")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfSites")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfUsers")
                        .HasColumnType("int");

                    b.HasKey("QuotationId", "ModuleName");

                    b.HasIndex("ModuleName");

                    b.ToTable("QuotationModules", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationTimeEstimateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("EndWeek")
                        .HasColumnType("tinyint");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuotationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("StartWeek")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId", "ModuleName", "StageKey")
                        .IsUnique();

                    b.ToTable("QuotationTimeEstimates", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.AdditionalScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ModulesId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<int>("NoOfManpower")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuotationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ModulesId");

                    b.HasIndex("QuotationId");

                    b.ToTable("AdditionalScopes", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.CompanyBankAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_no");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Ifsc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ifsc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("MsmeNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("msme_no");

                    b.HasKey("Id");

                    b.ToTable("company_bank_accounts", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.CompanyProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("DefaultTermsOfSale")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_terms_of_sale");

                    b.Property<string>("Gstn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gstn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("StateCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_code");

                    b.HasKey("Id");

                    b.ToTable("company_profile", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gstn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gstn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state_code");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.CustomerModuleSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualEscalationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialPurchasePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceId");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRenewalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RenewalPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("CustomerModuleSubscription", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.GstRateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CgstPct")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cgst_pct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("IgstPct")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("igst_pct");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<decimal>("SgstPct")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sgst_pct");

                    b.HasKey("Id");

                    b.ToTable("gst_rates", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceBankDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("account_no");

                    b.Property<string>("AccountType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ifsc");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("MsmeNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("msme_no");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("invoice_bank_details", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalScopesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_scopes_json");

                    b.Property<string>("AmountInWords")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("amount_in_words");

                    b.Property<string>("BuyerAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerGstn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("buyer_gstn");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("buyer_state");

                    b.Property<string>("BuyerStateCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("buyer_state_code");

                    b.Property<decimal>("CgstPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cgst_pct");

                    b.Property<int?>("CompanyProfileId")
                        .HasColumnType("int")
                        .HasColumnName("company_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("grand_total");

                    b.Property<int?>("GstRateId")
                        .HasColumnType("int")
                        .HasColumnName("gst_rate_id");

                    b.Property<string>("HsnCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hsn_code");

                    b.Property<decimal>("IgstPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("igst_pct");

                    b.Property<decimal>("Insurance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("insurance");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_no");

                    b.Property<string>("PlaceOfSupply")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("place_of_supply");

                    b.Property<int?>("PoId")
                        .HasColumnType("int")
                        .HasColumnName("po_id");

                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quotation_id");

                    b.Property<bool>("ReverseCharge")
                        .HasColumnType("bit")
                        .HasColumnName("reverse_charge");

                    b.Property<string>("SacCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sac_code");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("SellerAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerGstn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seller_gstn");

                    b.Property<string>("SellerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("seller_state");

                    b.Property<string>("SellerStateCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seller_state_code");

                    b.Property<decimal>("SgstPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sgst_pct");

                    b.Property<string>("ShipToAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ship_to_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TdsPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tds_pct");

                    b.Property<string>("TermsOfSale")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("terms_of_sale");

                    b.Property<string>("TimeOfIssue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("time_of_issue");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("QuotationId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasTrigger("trg_invoice_requires_verified_po");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DiscountAmount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DiscountPercentage");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("qty");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("rate");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uom");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModuleId");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.ModulePricingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualEscalationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InitialPurchasePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleId");

                    b.Property<DateTime>("PricingEffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PricingEffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("RenewalPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModulePricing", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.PoAuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoId");

                    b.ToTable("PoAuditLog", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("default_rate");

                    b.Property<string>("HsnSac")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hsn_sac");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uom");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.PurchaseOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("attachment_url");

                    b.Property<string>("ClientPoAdditionalScopes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_po_additional_scopes");

                    b.Property<decimal?>("ClientPoAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("client_po_amount");

                    b.Property<DateTime?>("ClientPoDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("client_po_date");

                    b.Property<string>("ClientPoItems")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_po_items");

                    b.Property<string>("ClientPoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("client_po_number");

                    b.Property<string>("ClientPoTerms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_po_terms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryTerms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_terms");

                    b.Property<string>("FileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file_content_type");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_terms");

                    b.Property<DateTime>("PoDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("po_date");

                    b.Property<string>("PoDirection")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("po_direction");

                    b.Property<string>("PoNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("po_no");

                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quotation_id");

                    b.Property<DateTime?>("QuotationRefDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("quotation_ref_date");

                    b.Property<string>("QuotationRefNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quotation_ref_no");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at");

                    b.Property<string>("ReceivedFromEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("received_from_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("UploadedFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("uploaded_file_name");

                    b.Property<string>("UploadedFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("uploaded_file_path");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verification_notes");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_by");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PoNo")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", null, t =>
                        {
                            t.HasTrigger("trg_po_verification_history");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuotationApp.API.Models.PurchaseOrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("ImplementationPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("implementation_price");

                    b.Property<decimal>("ModulePrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("module_price");

                    b.Property<int>("PoId")
                        .HasColumnType("int")
                        .HasColumnName("po_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("qty");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("rate");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uom");

                    b.HasKey("Id");

                    b.HasIndex("PoId");

                    b.ToTable("po_items", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.ReferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("references", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderBillingScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("MilestoneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SalesOrderId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("SalesOrderBillingSchedule", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("SalesOrderDocuments", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BillingCycle")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BillingType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("OneTime");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<string>("CustomerGstin")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CustomerPoDate")
                        .HasColumnType("date");

                    b.Property<string>("CustomerPoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasMismatch")
                        .HasColumnType("bit");

                    b.Property<decimal>("IgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("InvoicedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterState")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("MismatchRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTermsText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PlaceOfSupplyState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RenewalReminderDays")
                        .HasColumnType("int");

                    b.Property<int?>("RenewalTermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("RoundOff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SoDate")
                        .HasColumnType("date");

                    b.Property<string>("SoNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SubscriptionEnd")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SubscriptionStart")
                        .HasColumnType("date");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TermsTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PurchaseOrderId")
                        .IsUnique()
                        .HasFilter("[Status] <> 'Cancelled' AND [IsDeleted] = 0");

                    b.HasIndex("QuotationId");

                    b.HasIndex("SoDate");

                    b.HasIndex("SoNumber")
                        .IsUnique();

                    b.HasIndex("TermsTemplateId");

                    b.HasIndex("VerifiedBy");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("SalesOrders", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GstPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("GstRateId")
                        .HasColumnType("int");

                    b.Property<string>("HsnSacCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("IgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PoUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyInvoiced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QuotedUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SgstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Uom")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GstRateId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("SalesOrderId", "LineNo")
                        .IsUnique();

                    b.ToTable("SalesOrderItems", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderNumberSeriesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("SO");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYear")
                        .IsUnique();

                    b.ToTable("SalesOrderNumberSeries", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("SalesOrderId", "ChangedOn");

                    b.ToTable("SalesOrderStatusHistory", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SubscriptionPaymentHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPaymentHistory", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SubscriptionRenewalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EscalationPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PreviousAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("QuotationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RenewalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("RenewalYear")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "RenewalYear")
                        .IsUnique();

                    b.ToTable("SubscriptionRenewal", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.SupplierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Gstn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gstn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("state_code");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Models.TermsTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("terms_templates", (string)null);
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationModuleEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Data.ModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("ModuleName")
                        .HasPrincipalKey("ModuleName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Data.QuotationEntity", null)
                        .WithMany("QuotationModules")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationTimeEstimateEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Data.QuotationEntity", null)
                        .WithMany("QuotationTimeEstimates")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuotationApp.API.Models.AdditionalScope", b =>
                {
                    b.HasOne("QuotationApp.API.Data.ModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("ModulesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Data.QuotationEntity", null)
                        .WithMany("AdditionalScopes")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuotationApp.API.Models.CustomerModuleSubscriptionEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.InvoiceEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Data.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceBankDetailEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.InvoiceEntity", "Invoice")
                        .WithOne("BankDetails")
                        .HasForeignKey("QuotationApp.API.Models.InvoiceBankDetailEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.CustomerEntity", null)
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Data.QuotationEntity", null)
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", null)
                        .WithMany("Invoices")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceItemEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.InvoiceEntity", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Data.ModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuotationApp.API.Models.ModulePricingEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Data.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("QuotationApp.API.Models.PoAuditLogEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.PurchaseOrderEntity", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("QuotationApp.API.Models.PurchaseOrderEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.CustomerEntity", null)
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.SupplierEntity", null)
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QuotationApp.API.Models.PurchaseOrderItemEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.PurchaseOrderEntity", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderBillingScheduleEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.InvoiceEntity", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", "SalesOrder")
                        .WithMany("BillingSchedule")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderDocumentEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", "SalesOrder")
                        .WithMany("Documents")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.CompanyBankAccountEntity", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Data.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.CustomerEntity", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.PurchaseOrderEntity", "PurchaseOrder")
                        .WithMany("SalesOrders")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Data.QuotationEntity", "Quotation")
                        .WithMany("SalesOrders")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Models.TermsTemplateEntity", "TermsTemplate")
                        .WithMany()
                        .HasForeignKey("TermsTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Data.UserEntity", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BankAccount");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Quotation");

                    b.Navigation("TermsTemplate");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderItemEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.GstRateEntity", "GstRate")
                        .WithMany()
                        .HasForeignKey("GstRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Data.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GstRate");

                    b.Navigation("Module");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderStatusHistoryEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Data.UserEntity", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuotationApp.API.Models.SalesOrderEntity", "SalesOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SubscriptionPaymentHistoryEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.InvoiceEntity", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuotationApp.API.Models.CustomerModuleSubscriptionEntity", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SubscriptionRenewalEntity", b =>
                {
                    b.HasOne("QuotationApp.API.Models.CustomerModuleSubscriptionEntity", "Subscription")
                        .WithMany("Renewals")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("QuotationApp.API.Data.QuotationEntity", b =>
                {
                    b.Navigation("AdditionalScopes");

                    b.Navigation("QuotationModules");

                    b.Navigation("QuotationTimeEstimates");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("QuotationApp.API.Models.CustomerEntity", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("QuotationApp.API.Models.CustomerModuleSubscriptionEntity", b =>
                {
                    b.Navigation("Renewals");
                });

            modelBuilder.Entity("QuotationApp.API.Models.InvoiceEntity", b =>
                {
                    b.Navigation("BankDetails");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("QuotationApp.API.Models.PurchaseOrderEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SalesOrderEntity", b =>
                {
                    b.Navigation("BillingSchedule");

                    b.Navigation("Documents");

                    b.Navigation("Invoices");

                    b.Navigation("Items");

                    b.Navigation("StatusHistory");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("QuotationApp.API.Models.SupplierEntity", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
